/** 
 * @name 卡牌名称
 * @attr 卡牌的五行属性
 * @cost 使用卡牌所需费用
 * @imgUrl  卡牌插画
 * @effect 卡牌效果
 * @attack 攻击力
 * @health 生命值
 * @quality 卡牌的品质
 * @category 卡牌类别
*/
const CardList = [
    {
        name: '织女',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/zhinv.png'),
        effect: '1：使一个生灵攻击力-3，直到敌方回合结束',
        attack: '1',
        health: '9',
        quality: '凡',
        category: '天仙',
    },
    {
        name: '纠察灵官',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/jiuchalingguan.png'),
        effect: '敌方生灵的攻击力减一',
        attack: '0',
        health: '9',
        quality: '地',
        category: '天将',
    },
    {
        name: '玉兔',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/yutu.png'),
        effect: '免疫攻击伤害',
        attack: '2',
        health: '7',
        quality: '天',
        category: '妖仙',
    },
    {
        name: '棍僧',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/gunseng.png'),
        effect: '群攻对峙生灵及其相邻生灵',
        attack: '2',
        health: '9',
        quality: '凡',
        category: '佛门',
    },
    {
        name: '峨眉女尼',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/emeinvni.png'),
        effect: '免疫非攻击伤害',
        attack: '3',
        health: '7',
        quality: '凡',
        category: '佛门',
    },
    {
        name: '悬壶医女',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/xuanhuyinv.png'),
        effect: '进场时：使一个生灵的生命加三',
        attack: '3',
        health: '7',
        quality: '凡',
        category: '异人',
    },
    {
        name: '天庭甲士',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/tiantingjiashi.png'),
        effect: '进场时：使一个己方生灵的攻击加一',
        attack: '2',
        health: '7',
        quality: '地',
        category: '天将',
    },
    {
        name: '蔡文姬',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/caiwenji.png'),
        effect: '己方主角的生命<=17时，己方生灵受到的伤害-1',
        attack: '3',
        health: '7',
        quality: '凡',
        category: '异人',
    },
    {
        name: '吐宝鼠',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/tubaoshu.png'),
        effect: '死亡时：己方主角生命+2，并获得一张灵玉',
        attack: '2',
        health: '8',
        quality: '天',
        category: '神兽',
    },
    {
        name: '气疗术',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/qiliaoshu.png'),
        effect: '己方主角生命+2，抽一张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '法术',
    },
    {
        name: '五气朝元',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/wuqichaoyuan.png'),
        effect: '耗尽法力：己方主角的生命值+2x，x为消耗的法力值，然后法力值+1',
        attack: '',
        health: '',
        quality: '凡',
        category: '法术',
    },
    {
        name: '反噬',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/fanshi.png'),
        effect: '使一个生灵获得反弹直到敌方回合结束，再抽一张牌。',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '碎羽祭',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/suiyuji.png'),
        effect: '消灭己方的一个装备，来消灭连锁区的生灵和装备卡',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '圣兽守护',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/shengshoushouhu.png'),
        effect: '使一个生灵免疫非攻击伤害直到敌方回合结束，再抽一张牌',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '破玉爪',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/poyuzhua.png'),
        effect: '消灭一个己方装备，再抽两张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '禅海截心',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/chanhaijiexin.png'),
        effect: '己方主角生命+6，敌方修为比己方>=2时，获得一张截心咒',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '妙法莲华',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/miaofalianhua.png'),
        effect: '将本回合内己方进入废牌堆的生灵放入己方手牌',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '六字大明咒',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/liuzidamingzhou.png'),
        effect: '敌方打出装备牌时触发：将该装备放入己方手牌，再抽一张牌',
        attack: '',
        health: '',
        quality: '地',
        category: '触发法术',
    },
    {
        name: '燕双飞',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/yanshuangfei.png'),
        effect: '依次选择两个生灵：第一个生命+4，第二个+8',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '禅定',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/chanding.png'),
        effect: '使一个生灵沉睡。或者使一个生灵的相邻生灵沉睡，直到敌方回合结束',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '食梦',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/shimeng.png'),
        effect: '抽一张卡，己方主角生命值增加场上沉睡生灵数x2',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '浩然正气',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/haoranzhengqi.png'),
        effect: '己方所有生灵获得反弹，直到敌方回合结束',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '闭口禅',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/bikouchan.png'),
        effect: '选择一个己方生灵，并抽一张牌。若所选生灵生命值等于1，则所有己方生灵生命回满',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '拈花指',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/nianhuazhi.png'),
        effect: '从敌方牌库中选择一张装备卡放入己方手牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '法术',
    },
    {
        name: '落日神箭',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/luorishenjian.png'),
        effect: '消灭一个带有装备的生灵',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '再造',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/zaizao.png'),
        effect: '复制一个场上的非金系的装备放入己方手牌',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '坐禅',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/zuochan.png'),
        effect: '获得1+x张风火蒲团，敌方修为每比己方高2，x+1',
        attack: '',
        health: '',
        quality: '天',
        category: '法术',
    },
    {
        name: '祛邪佛光',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/quxiefoguang.png'),
        effect: '抽一张牌，借力：消灭所有费用<=2的衍生生灵',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '上上签',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/shangshangqian.png'),
        effect: '将己方手牌和牌库的同名卡放入废牌堆，再抽一张卡，若当前为偶数回合，则己方法力+2',
        attack: '',
        health: '',
        quality: '凡',
        category: '法术',
    },
    {
        name: '天庭禁令',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/tiantingjinling.png'),
        effect: '本回合内，敌方最多只能抽一张卡。（连锁区有牌时才能使用）',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '宝玉招财',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/baoyuzhaocai.png'),
        effect: '己方生命+3，获得一张灵玉',
        attack: '',
        health: '',
        quality: '地',
        category: '法术',
    },
    {
        name: '千里婵娟-纪',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/qianlichanjuan.png'),
        effect: '本回合内己方主角恢复生命时：再恢复一次相同数量的生命',
        attack: '',
        health: '',
        quality: '天',
        category: '法术',
    },
    {
        name: '九环锡杖',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/jiuhuanxizhang.png'),
        effect: '己方回合开始时：若己方主角的生命<9，则生命+9',
        attack: '',
        health: '',
        quality: '天',
        category: '主角装备',
    },
    {
        name: '锦襕袈裟',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/jinglanjiasha.png'),
        effect: '操控者，所装备生灵及其相邻生灵所受到的非攻击伤害-4',
        attack: '',
        health: '',
        quality: '天',
        category: '生灵装备',
    },
    {
        name: '仙豆',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/xiandou.png'),
        effect: '己方主角受到攻击伤害后：生命+1',
        attack: '',
        health: '',
        quality: '地',
        category: '主角装备',
    },
    {
        name: '岐牛神鼓',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/qiniushengu.png'),
        effect: '锁装备生灵及其相邻生灵获得反弹',
        attack: '',
        health: '',
        quality: '凡',
        category: '生灵装备',
    },
    {
        name: '刀盾',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/daodun.png'),
        effect: '所装备生灵获得反弹，且免疫敌方造成的非攻击伤害',
        attack: '',
        health: '',
        quality: '凡',
        category: '生灵装备',
    },
    {
        name: '五行月饼-纪',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/wuxingyuebing.png'),
        effect: '己方回合开始时：己方主角和生灵生命+1，从场上进入废牌堆时，改为放入敌方手牌',
        attack: '',
        health: '',
        quality: '天',
        category: '主角装备',
    },
    {
        name: '羊力大仙',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/yanglidaxian.png'),
        effect: '击伤对手后：攻击+1',
        attack: '2',
        health: '10',
        quality: '凡',
        category: '妖怪',
    },
    {
        name: '小猴精',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/xiaohoujing.png'),
        effect: '己方生灵数量>=3时，攻击+2',
        attack: '1',
        health: '10',
        quality: '凡',
        category: '妖怪',
    },
    {
        name: '青牛精',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/qinniujing.png'),
        effect: '对峙生灵费用>=4时，本生灵不能攻击',
        attack: '4',
        health: '7',
        quality: '地',
        category: '妖仙',
    },
    {
        name: '月宫小强',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/yuegongxiaoqiang.png'),
        effect: '1：牺牲：在相邻空位衍生同名生灵',
        attack: '3',
        health: '3',
        quality: '天',
        category: '异灵',
    },
    {
        name: '铁背苍狼精',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/tiebeicanglangjing.png'),
        effect: '衍生生灵进场时：本生灵攻击+1，生命-1',
        attack: '2',
        health: '11',
        quality: '凡',
        category: '妖怪',
    },
    {
        name: '杏仙',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/xingxian.png'),
        effect: '',
        attack: '3',
        health: '7',
        quality: '凡',
        category: '妖仙',
    },
    {
        name: '蜘蛛精',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/zhizhujing.png'),
        effect: '死亡时：在原位置衍生一个随机的一废生灵',
        attack: '2',
        health: '6',
        quality: '地',
        category: '妖怪',
    },
    {
        name: '凤翼天翔',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/fengyitianxiang.png'),
        effect: '使一个生灵获得穿透，直到回合结束',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '天山折梅',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/tianshanzhemei.png'),
        effect: '复制一个敌方生灵或者一个己方木系生灵到己方手牌',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '枯木生花',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/kumushenghua.png'),
        effect: '使一个生灵的攻击+2，并将敌方废牌堆所有卡牌移除游戏',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '落花流水',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/luohualiushui.png'),
        effect: '敌方回合内，己方弃牌时触发：己方抽三张牌',
        attack: '',
        health: '',
        quality: '地',
        category: '触发法术',
    },
    {
        name: '倒卷帘',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/daojuanlian.png'),
        effect: '敌方打出费用>=5的法术牌时触发：消灭该法术',
        attack: '',
        health: '',
        quality: '天',
        category: '触发法术',
    },
    {
        name: '祝由秘技',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/zhuyoumiji.png'),
        effect: '己方主角生命+x，x为己方修为',
        attack: '',
        health: '',
        quality: '地',
        category: '法术',
    },
    {
        name: '同气连枝',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/tongqilianzhi.png'),
        effect: '选择一个生灵，使所有生灵的类别变为与其相同，再抽一张牌',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '叠翠',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/diecui.png'),
        effect: '使一个生灵攻击次数+1，直到回合结束',
        attack: '',
        health: '',
        quality: '天',
        category: '法术',
    },
    {
        name: '碾压',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/nianya.png'),
        effect: '使所有己方生灵攻击+1，并获得透骨，直到回合结束',
        attack: '',
        health: '',
        quality: '地',
        category: '法术',
    },
    {
        name: '野狐禅',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/yehuchan.png'),
        effect: '敌方打出的法术与己方场上某生灵费用相同时触发：消灭该法术，己方修为+1',
        attack: '',
        health: '',
        quality: '地',
        category: '触发法术',
    },
    {
        name: '枯荣决',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/kurongjue.png'),
        effect: '若敌方修为比己方修为多2点及以上，则己方修为+2',
        attack: '',
        health: '',
        quality: '天',
        category: '法术',
    },
    {
        name: '西天取经',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/xitianqujing.png'),
        effect: '若己方场上同时存在唐三藏，沙和尚，孙悟空，猪八戒。则己方获得胜利',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '昙花一现',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/tanhuayixian.png'),
        effect: '敌方打出3费卡牌时，若己方生灵数>=敌方时触发：消灭该卡牌',
        attack: '',
        health: '',
        quality: '天',
        category: '触发法术',
    },
    {
        name: '子夜留香',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/ziyeliuxiang.png'),
        effect: '若敌方修为>=己方，则己方修为+1，否则双方修为+1',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '封禅',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/fengshan.png'),
        effect: '封印一个己方生灵再抽一张卡。或封印己方所有生灵再抽一张卡',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '绝处逢生',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/juechufengsheng.png'),
        effect: '己方主角生命+5，若没有手牌，则抽一张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '触景生情',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/chujingshengqing.png'),
        effect: '从己方牌库中选择一张触发法术放入己方手牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '法术',
    },
    {
        name: '书山有路',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/shushanyoulu.png'),
        effect: '抽一张牌，直到回合结束，己方生灵每使用一次主动技能攻击永久+1',
        attack: '',
        health: '',
        quality: '凡',
        category: '法术',
    },
    {
        name: '恶作剧',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/ezuoju.png'),
        effect: '敌方打出装备牌时触发：消灭该装备，并将牌库中一张随机妖仙生灵加入手牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '触发法术',
    },
    {
        name: '山中无老虎',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/shanzhongwulaohu.png'),
        effect: '本卡被弃掉时触发：在己方随机空位衍生小猴精，再抽一张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '触发法术',
    },
    {
        name: '借力打力',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/jielidali.png'),
        effect: '使一个生灵攻击+1，下一个己方回合开始时：获得一张同名衍生卡',
        attack: '',
        health: '',
        quality: '地',
        category: '法术',
    },
    {
        name: '撞心杵',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/zhuangxinchu.png'),
        effect: '所装备生灵获得：攻击力+1，若被阻挡则改为+4',
        attack: '',
        health: '',
        quality: '凡',
        category: '生灵装备',
    },
    {
        name: '瑶光核桃',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/yaoguanghetao.png'),
        effect: '所装备生灵的攻击+2，其他己方生灵的攻击+1',
        attack: '',
        health: '',
        quality: '地',
        category: '生灵装备',
    },
    {
        name: '攒心钉',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/zanxinding.png'),
        effect: '所装备生灵获得透骨',
        attack: '',
        health: '',
        quality: '地',
        category: '生灵装备',
    },
    {
        name: '清肠稻',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/qingchangdao.png'),
        effect: '所装备生灵每回合可多使用一次生灵技能',
        attack: '',
        health: '',
        quality: '地',
        category: '生灵装备',
    },
    {
        name: '盘龙拐',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/panlongguai.png'),
        effect: '非衍生的己方生灵进场时，所装备生灵攻击+1',
        attack: '',
        health: '',
        quality: '凡',
        category: '生灵装备',
    },
    {
        name: '人参果',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/renshengguo.png'),
        effect: '所装备生灵获得：操控者回合结束时：生命+4',
        attack: '',
        health: '',
        quality: '地',
        category: '生灵装备',
    },
    {
        name: '紫金铃',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/zijinling.png'),
        effect: '0：选择两个生灵，使第一个生灵的类别变为与第二个生灵一致',
        attack: '',
        health: '',
        quality: '凡',
        category: '生灵装备',
    },
    {
        name: '斩妖剑',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/zhanyaojian.png'),
        effect: '与所装备生灵相同类别的所有己方生灵的攻击+2',
        attack: '',
        health: '',
        quality: '凡',
        category: '生灵装备',
    },
    {
        name: '如意钩',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/ruyigou.png'),
        effect: '所装备生灵获得：对其他生灵造成的伤害+2',
        attack: '',
        health: '',
        quality: '凡',
        category: '生灵装备',
    },
    {
        name: '五行粽子-纪',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/ruyigou.png'),
        effect: '己方回合开始时：使一个生灵攻击+2，直到回合结束，从场上进入废牌堆是：改为放入敌方手牌',
        attack: '',
        health: '',
        quality: '天',
        category: '主角装备',
    },
    {
        name: '龟丞相：天明',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/guichengxiang.png'),
        effect: '进场时：抽一张牌',
        attack: '0',
        health: '8',
        quality: '凡',
        category: '水族',
    },
    {
        name: '逍遥笛仙',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/xiaoyaodixian.png'),
        effect: '受到攻击伤害且未死亡时：回手。1：进入己方其他空位',
        attack: '2',
        health: '6',
        quality: '凡',
        category: '散仙',
    },
    {
        name: '量人蛇',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/liangrenshe.png'),
        effect: '1：使一个生命小于等于本生灵的敌方生灵回手',
        attack: '1',
        health: '10',
        quality: '天',
        category: '神兽',
    },
    {
        name: '美人鱼',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/meirenyu.png'),
        effect: '进场时：与一个己方生灵换位',
        attack: '2',
        health: '9',
        quality: '凡',
        category: '水族',
    },
    {
        name: '龙宫密探',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/longgongmitan.png'),
        effect: '进场时：查看敌方牌库顶的三张牌',
        attack: '2',
        health: '9',
        quality: '凡',
        category: '水族',
    },
    {
        name: '龙鲤',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/longli.png'),
        effect: '6，延迟：牺牲，在原位置衍生天池幻龙',
        attack: '2',
        health: '9',
        quality: '地',
        category: '水族',
    },
    {
        name: '玉扇仙女',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/yushanxiannv.png'),
        effect: '进场时：若己方门派为天宫，则从己方牌库中复制5张卡牌洗入牌库',
        attack: '3',
        health: '7',
        quality: '天',
        category: '天仙',
    },
    {
        name: '猪婆龙',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/zhupolong.png'),
        effect: '穿透',
        attack: '2',
        health: '8',
        quality: '凡',
        category: '神兽',
    },
    {
        name: '螺旋劲',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/luoxuanjing.png'),
        effect: '使一个生灵与其装备一起回手',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '暗潮',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/anchao.png'),
        effect: '单回合内敌方第二次打出法术牌时触发：将该法术放入己方手牌',
        attack: '',
        health: '',
        quality: '天',
        category: '触发法术',
    },
    {
        name: '心血来潮',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/xinxuelaichao.png'),
        effect: '任意一方打出法术牌后，若联锁区卡牌数量>=3，触发：消灭连锁区的所有敌方法术牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '触发法术',
    },
    {
        name: '对对符',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/duiduifu.png'),
        effect: '抽一张牌；若己方6个生灵的费用都与其对峙生灵相同，则己方获得胜利',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '灵气旋涡',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/lingqixuanwo.png'),
        effect: '抽一张牌；消灭连锁区中以费用大于或等于5的场上生灵为目标的法术牌',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '神龙摆尾',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/shenlongbaiwei.png'),
        effect: '使一个生灵右侧的所有己方生灵回手',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '牵引术',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/qianyinshu.png'),
        effect: '连锁区中以场上生灵为目标的法术，全部重新随机指定其目标',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '乱环诀',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/luanhuanjue.png'),
        effect: '为敌方牌库顶的4张牌排序，再消灭第一张',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '小旋风',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/xiaoxuanfeng.png'),
        effect: '使任意一方所有生灵同时向右移动一格，（最右侧的生灵移动到最左侧），双方再各抽一张牌',
        attack: '',
        health: '',
        quality: '地',
        category: '法术',
    },
    {
        name: '摩云袖-纪',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/moyunxiu.png'),
        effect: '从敌方废牌堆中选择两张牌置于敌方牌库顶，己方再抽一张牌',
        attack: '',
        health: '',
        quality: '天',
        category: '法术',
    },
    {
        name: '替死符',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/tisifu.png'),
        effect: '选择一个生灵，使其获得：替施法者承受非攻击伤害，直到回合结束。再抽一张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '浪淘沙',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/langtaosha.png'),
        effect: '消灭己方牌库顶三张牌中的生灵牌，再抽一张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '炼精化气',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/lianjinghuaqi.png'),
        effect: '抽一张牌，双方法力+1',
        attack: '',
        health: '',
        quality: '地',
        category: '法术',
    },
    {
        name: '问道',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/wendao.png'),
        effect: '使一个没有主动技能的生灵复制一个生灵的主动技能，双方各抽一张牌',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '止水',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/zhishui.png'),
        effect: '消灭连锁区的上一张费用<=2的法术牌',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '惊鸿一瞥',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/jinghongyipie.png'),
        effect: '查看己方牌库顶的两张牌，选择其中一张放入手牌，另外一张置于牌库底',
        attack: '',
        health: '',
        quality: '天',
        category: '法术',
    },
    {
        name: '梦幻泡影',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/menghuanpaoying.png'),
        effect: '从敌方手牌中选择一张牌洗入敌方牌库并洗牌，然后敌方抽一张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '遮天',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/zhetian.png'),
        effect: '己方生灵不再能被选为目标，直到敌方回合结束，再抽一张牌',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '红杏出墙',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/hongxingchuqiang.png'),
        effect: '抽一张牌，将一张杏仙放入敌方牌库并洗牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '炼神还虚',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/lianshenhuanxu.png'),
        effect: '抽一张牌，然后弃掉手牌中所有灵玉并抽等量的牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '法术',
    },
    {
        name: '炼气化神',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/lianqihuashen.png'),
        effect: '抽一张牌，耗尽法力，每消耗两点就获得一张灵玉',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '定海神珠',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/dinghaishenzhu.png'),
        effect: '1：手牌小于等于6的玩家抽一张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '主角装备',
    },
    {
        name: '五仙汤',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/wuxiantang.png'),
        effect: '己方打出3费法术牌后，若己方当前法力小于等于己方修为，则己方法力+1（一回合十次）',
        attack: '',
        health: '',
        quality: '地',
        category: '主角装备',
    },
    {
        name: '扫霞衣',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/saoxiayi.png'),
        effect: '所装备生灵获得：受到攻击伤害且为死亡时：本生灵回手，再将对峙生灵放回其操控者的牌库顶',
        attack: '',
        health: '',
        quality: '地',
        category: '生灵装备',
    },
    {
        name: '金丹砂',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/jindansha.png'),
        effect: '敌方生灵无法速攻，穿透，吸血',
        attack: '',
        health: '',
        quality: '地',
        category: '主角装备',
    },
    {
        name: '遁龙桩',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/dunlongzhuang.png'),
        effect: '所装备生灵获得：操控者回合开始时：与一个己方生灵换位',
        attack: '',
        health: '',
        quality: '地',
        category: '生灵装备',
    },
    {
        name: '玲珑内丹',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/linglongneidan.png'),
        effect: '己方回合开始时：若己方没有手牌，则额外抽一张牌',
        attack: '',
        health: '',
        quality: '地',
        category: '生灵装备',
    },
    {
        name: '观星仪',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/guanxingyi.png'),
        effect: '进场时：借力：抽一张牌；1为己方牌库顶的三张牌排序',
        attack: '',
        health: '',
        quality: '天',
        category: '主角装备',
    },
    {
        name: '精囊妙计',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/jingnangmiaoji.png'),
        effect: '己方回合开始时，若场上有费用>=6的生灵，则消灭本装备并选择牌库中一张法术牌加入手牌',
        attack: '',
        health: '',
        quality: '天',
        category: '主角装备',
    },
    {
        name: '天煞星',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/tianshaxing.png'),
        effect: '进场时：若己方修为<=1，则己方主角的生命-3',
        attack: '3',
        health: '9',
        quality: '凡',
        category: '神官',
    },
    {
        name: '精卫鸟',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/jingweiniao.png'),
        effect: '还击',
        attack: '2',
        health: '9',
        quality: '凡',
        category: '神兽',
    },
    {
        name: '牛虱',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/niushi.png'),
        effect: '速攻；击伤对手后：本生灵生命-3',
        attack: '3',
        health: '6',
        quality: '凡',
        category: '妖怪',
    },
    {
        name: '武吉',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/wuji.png'),
        effect: '本生灵给对手造成的攻击伤害加倍',
        attack: '2',
        health: '10',
        quality: '天',
        category: '异人',
    },
    {
        name: '闪电貂',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/shandiandiao.png'),
        effect: '进场时：本生灵的生命-2',
        attack: '3',
        health: '9',
        quality: '凡',
        category: '雷神',
    },
    {
        name: '单雄信',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/shanxiongxin.png'),
        effect: '速攻；己方回合开始时，若己方场上有攻击>=5的生灵，攻击+1，直到回合结束',
        attack: '2',
        health: '9',
        quality: '凡',
        category: '英魂',
    },
    {
        name: '雷霆一击',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/leitingyiji.png'),
        effect: '若敌方修为大于己方，则敌方修为-1，否则双方修为-1',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '逆修斩',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/nixiuzhan.png'),
        effect: '敌方使用法术抽牌时触发：敌方修为-1，己方抽一张牌',
        attack: '',
        health: '',
        quality: '地',
        category: '触发法术',
    },
    {
        name: '飞剑',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/feijian.png'),
        effect: '使一个生灵的生命-8',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '霹雳火',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/pilihuo.png'),
        effect: '对手生命-5',
        attack: '',
        health: '',
        quality: '凡',
        category: '法术',
    },
    {
        name: '雷霆一击',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/leitingyiji.png'),
        effect: '耗尽法力：对手的生命值-x，x为消耗的法力，之后抽一张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '法术',
    },
    {
        name: '悲魔残光',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/beimocanguang.png'),
        effect: '敌方使用生灵技能时触发：该生灵的生命-9，己方抽一张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '触发法术',
    },
    {
        name: '腥风破',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/xingfengpo.png'),
        effect: '敌方使用生灵技能时触发：该生灵的生命-9，己方抽一张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '天马流星',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/tianmaliuxing.png'),
        effect: '敌方使用生灵技能时触发：该生灵的生命-9，己方抽一张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '火灵封',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/huolingfeng.png'),
        effect: '敌方法力-5，己方抽一张牌',
        attack: '',
        health: '',
        quality: '地',
        category: '法术',
    },
    {
        name: '梦痕剑影',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/menghenjianying.png'),
        effect: '所有沉睡生灵的对峙生灵的生命-15，抽一张卡',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '天罚',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/tianfa.png'),
        effect: '若地方修为>=7，则其修为-2；若其修为>=12，则改为-4',
        attack: '',
        health: '',
        quality: '天',
        category: '法术',
    },
    {
        name: '血之凝视',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/xuezhiningshi.png'),
        effect: '攻击小于或等于1的地方生灵进场时触发：该生灵的生命-20，己方抽一张牌',
        attack: '',
        health: '',
        quality: '天',
        category: '触发法术',
    },
    {
        name: '以牙还牙',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/yiyahuanya.png'),
        effect: '使一个生灵获得还击，直到敌方回合结束，再抽一张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '乱剑',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/luanjian.png'),
        effect: '造成三次伤害，每次随机使一个敌方生灵的生命-3',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '剑雨无声',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/jianyuwusheng.png'),
        effect: '对手增加其生命时触发：己方抽一张牌，且本回合内，对手的生命值每增加多少就会损失多少',
        attack: '',
        health: '',
        quality: '凡',
        category: '触发法术',
    },
    {
        name: '赤月颂',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/chiyuesong.png'),
        effect: '双方分别从各自废牌堆选择一张法术牌加入手牌（双方废牌堆中都有法术牌时才能使用）',
        attack: '',
        health: '',
        quality: '天',
        category: '法术',
    },
    {
        name: '化为灰烬',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/huaweihuijing.png'),
        effect: '消灭一个装备，再消灭地方牌库顶的牌直到剩下35张',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '降妖宝杖',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/xiangyaobaozhang.png'),
        effect: '所装备生灵获得：攻击+1，且对其他生灵造成的攻击伤害加倍',
        attack: '',
        health: '',
        quality: '地',
        category: '生灵装备',
    },
    {
        name: '番天印',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/fantianyin.png'),
        effect: '4：使一个生灵的生命-5',
        attack: '',
        health: '',
        quality: '凡',
        category: '主角装备',
    },
    {
        name: '混元伞',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/hunyuansan.png'),
        effect: '所装备生灵及其相邻生灵获得：还击',
        attack: '',
        health: '',
        quality: '地',
        category: '生灵装备',
    },
    {
        name: '血芒珠',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/xuemangzhu.png'),
        effect: '木系或土系的己方生灵进场时：对手的生命-2',
        attack: '',
        health: '',
        quality: '天',
        category: '生灵装备',
    },
    {
        name: '火焰杯•稀',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/huoyanbei.png'),
        effect: '己方生灵进场和死亡时：其对峙生灵的生命-x，x为己方生灵的费用（最多三点）',
        attack: '',
        health: '',
        quality: '天',
        category: '主角装备',
    },
    {
        name: '伤心小刀',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/shangxinxiaodao.png'),
        effect: '1：使一个生灵获得：受到的非攻击伤害+4，直到回合结束',
        attack: '',
        health: '',
        quality: '地',
        category: '主角装备',
    },
    {
        name: '爆竹•纪',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/baozhu.png'),
        effect: '所装备生灵获得：操控者回合开始时：其生命-4，其相邻生灵的生命-2',
        attack: '',
        health: '',
        quality: '天',
        category: '生灵装备',
    },
    {
        name: '五色烟',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/wuseyan.png'),
        effect: '所装备生灵获得：操控者回合开始时：与本生灵五行相同的所有生灵的生命-2',
        attack: '',
        health: '',
        quality: '地',
        category: '生灵装备',
    },
    {
        name: '赤焰杖',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/chiyanzhang.png'),
        effect: '1：使一个生灵获得还击，直到地方回合结束',
        attack: '',
        health: '',
        quality: '天',
        category: '主角装备',
    },
    {
        name: '火龙标',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/huolongbiao.png'),
        effect: '所装备生灵获得：每回合首次使用技能后：使一个生灵的生命-3',
        attack: '',
        health: '',
        quality: '凡',
        category: '生灵装备',
    },
    {
        name: '纯阳剑',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/chunyangjian.png'),
        effect: '所装备生灵获得：击伤对手时：所有地方生灵的生命-3',
        attack: '',
        health: '',
        quality: '凡',
        category: '生灵装备',
    },
    {
        name: '柳叶飞刀',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/liuyefeidao.png'),
        effect: '敌方回合内，敌方生灵受到攻击伤害时：对手的生命-3',
        attack: '',
        health: '',
        quality: '地',
        category: '主角装备',
    },
    {
        name: '盗火钗',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/daohuocha.png'),
        effect: '所装备生灵获得：击伤对手时：将随机1张已被修炼的法术牌加入手牌',
        attack: '',
        health: '',
        quality: '天',
        category: '主角装备',
    },
    {
        name: '九龙神火罩',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/jiulongshenhuozhao.png'),
        effect: '己方回合结束时：所有生灵生命-1',
        attack: '',
        health: '',
        quality: '天',
        category: '主角装备',
    },
    {
        name: '罗刹',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/luosha.png'),
        effect: '进场时：消灭相邻生灵',
        attack: '',
        health: '',
        quality: '凡',
        category: '鬼吏',
    },
    {
        name: '骷髅仙',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/kulouxian.png'),
        effect: '己方回合结束时：己方主角的生命-1',
        attack: '',
        health: '',
        quality: '凡',
        category: '妖怪',
    },
    {
        name: '赤身鬼使',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/chishenguili.png'),
        effect: '本生灵被选为目标时：死亡',
        attack: '',
        health: '',
        quality: '凡',
        category: '鬼吏',
    },
    {
        name: '双尾蝎',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/shuangweixie.png'),
        effect: '2：使一个生灵的攻击-1，本生灵的攻击+1',
        attack: '',
        health: '',
        quality: '天',
        category: '神兽',
    },
    {
        name: '千年虫',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/qiannianchong.png'),
        effect: '攻击对峙生灵时：防止本次攻击伤害，对峙生灵生命变为1',
        attack: '',
        health: '',
        quality: '天',
        category: '异灵',
    },
    {
        name: '勾魂小鬼',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/gouhunxiaogui.png'),
        effect: '死亡时：消灭己方牌库顶的2张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '鬼吏',
    },
    {
        name: '蝠妖',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/fuyao.png'),
        effect: '己方场上存在其他具有吸血的生灵时：获得吸血',
        attack: '',
        health: '',
        quality: '凡',
        category: '妖怪',
    },
    {
        name: '引魂姬',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/yinghunji.png'),
        effect: '可放入敌方空位：1，本生灵生命-4；不能被己方卡牌或技能选为目标',
        attack: '',
        health: '',
        quality: '地',
        category: '鬼吏',
    },
    {
        name: '疫鬼',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/yigui.png'),
        effect: '死亡时：己方主角生命-X，X为本生灵的费用，并使对手场上1个费用最高随机生灵获得该效果',
        attack: '',
        health: '',
        quality: '地',
        category: '妖怪',
    },
    {
        name: '惊变',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/jingbian.png'),
        effect: '敌方回合内，敌方抽牌后，若其本回合抽牌数量大于或等于3，触发：敌方弃3张牌',
        attack: '',
        health: '',
        quality: '天',
        category: '触发法术',
    },
    {
        name: '九阴白骨爪',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/jiuyingbaiguzhua.png'),
        effect: '消灭一个己方生灵，再抽2张牌（若为衍生生灵则不抽牌）',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '往生无常',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/wangshengwuchang.png'),
        effect: '从敌方废牌堆中选择3张牌移出游戏，再抽一张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '舍身取义·纪',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/sheshenquyi.png'),
        effect: '使一个生灵获得：替相邻生灵承受伤害（不可减免），直到回合结束，再抽1张牌',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '落宝',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/luobao.png'),
        effect: '从己方废牌堆中选择1张生灵牌移出游戏，再消灭一个装备',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '亡命绝杀',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/wangmingjuesha.png'),
        effect: '弃x张牌，再消灭所有费用为X的敌方生灵',
        attack: '',
        health: '',
        quality: '地',
        category: '法术',
    },
    {
        name: '乱心尘',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/luanxinceng.png'),
        effect: '使一个被阻挡的生灵及其对峙生灵分别攻击各自的操控者',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '莫回首',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/mohuishou.png'),
        effect: '所有生灵不能回手，直到回合结束，抽1张牌',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '断水',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/duanshui.png'),
        effect: '二选一：敌方弃1张法术牌；或法力-2，选择敌方手牌中1张法术牌弃牌（需法力大于或等于3）',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '断肠吟',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/duanchangying.png'),
        effect: '依次选择一个满血的己方生灵和敌方生灵，使它们的生命变为1',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '聚灵斩',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/julingzhan.png'),
        effect: '选择一个生灵，使所有带有装备的生灵对其发动一轮攻击，己方再抽一张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '妖气冲天',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/yaoqichongtian.png'),
        effect: '所有己方妖怪类生灵的攻击+1，抽一张牌',
        attack: '',
        health: '',
        quality: '天',
        category: '法术',
    },
    {
        name: '藏剑术',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/changjianshu.png'),
        effect: '抽一张牌，再消灭己方牌库顶的三张牌',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '吸髓',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/xisui.png'),
        effect: '使具有吸血的己方生灵获得，己方主角和其他己方生灵增加等量的生命直到回合结束',
        attack: '',
        health: '',
        quality: '地',
        category: '法术',
    },
    {
        name: '北冥真气',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/beimingzhenqi.png'),
        effect: '使一个生灵获得吸血，直到回合结束，再抽一张牌',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '莫须有',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/moxuyou.png'),
        effect: '随机获得一张稀有卡',
        attack: '',
        health: '',
        quality: '天',
        category: '法术',
    },
    {
        name: '同醉',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/tongzui.png'),
        effect: '双方主角的生命-1，己方抽一张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '法术',
    },
    {
        name: '祛魅',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/qumei.png'),
        effect: '二选一：地方弃两张衍生牌；或消灭一个衍生生灵',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '落井下石',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/luojingxiashi.png'),
        effect: '地方生灵受到非攻击伤害时触发，该生灵生命-6，再抽一张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '触发法术',
    },
    {
        name: '独一无二',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/duyiwuer.png'),
        effect: '选择一个生灵，若场上有其他同名生灵，则消灭所选生灵',
        attack: '',
        health: '',
        quality: '凡',
        category: '法术',
    },
    {
        name: '脱尘烟',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/tuocengyan.png'),
        effect: '耗尽法力；使一个生灵变化为费用-x的随机生灵，x为消耗的法力，再抽一张牌（不触发进场和离场能力）',
        attack: '',
        health: '',
        quality: '天',
        category: '法术',
    },
    {
        name: '阴风袋',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/yingfengdai.png'),
        effect: '己方弃牌时：每弃一张牌就受到1点伤害；敌方弃牌时：每弃一张就受到2点伤害',
        attack: '',
        health: '',
        quality: '地',
        category: '主角装备',
    },
    {
        name: '暗火柱',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/anhuozhu.png'),
        effect: '己方主角受到攻击伤害后：对手的生命-1',
        attack: '',
        health: '',
        quality: '地',
        category: '主角装备',
    },
    {
        name: '醒酒毡',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/xingjiuzhan.png'),
        effect: '1：弃一张牌：己方主角的生命+5，可连续使用',
        attack: '',
        health: '',
        quality: '地',
        category: '主角装备',
    },
    {
        name: '邪云罩',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/xieyunzhao.png'),
        effect: '0：选择两个己方生命。互换其生命',
        attack: '',
        health: '',
        quality: '地',
        category: '主角装备',
    },
    {
        name: '聊斋志异',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/liaozhaizhiyi.png'),
        effect: '回合结束时，若本回合己方主角受到的非攻击伤害>=3，则随机获得一张随机聊斋生灵牌',
        attack: '',
        health: '',
        quality: '天',
        category: '主角装备',
    },
    {
        name: '生死簿',
        attr: 5,
        cost: 1,
        imgUrl: require('../assets/cardImg/shengsipu.png'),
        effect: '己方非衍生生灵死亡时：向己方牌库中洗入一张【因缘·信】',
        attack: '',
        health: '',
        quality: '地',
        category: '主角装备',
    },
    {
        name: '麻姑',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/magu.png'),
        effect: '1：牺牲，其生命转加给己方主角',
        attack: '2',
        health: '10',
        quality: '地',
        category: '天仙',
    },
    {
        name: '值日功曹',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/zhirigongcao.png'),
        effect: '反弹',
        attack: '2',
        health: '10',
        quality: '地',
        category: '天将',
    },
    {
        name: '黄巾力士',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/huangjinlishi.png'),
        effect: '反弹；1：进入己方其他空位',
        attack: '0',
        health: '15',
        quality: '凡',
        category: '天将',
    },
    {
        name: '天兵',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/tianbing.png'),
        effect: '群攻',
        attack: '1',
        health: '11',
        quality: '凡',
        category: '天将',
    },
    {
        name: '巨灵神',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/julingshen.png'),
        effect: '进场时：对峙生灵补满生命',
        attack: '3',
        health: '16',
        quality: '凡',
        category: '天将',
    },
    {
        name: '昴日鸡',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/mangriji.png'),
        effect: '3，牺牲：在原位置衍生【昴日星官】',
        attack: '2',
        health: '11',
        quality: '地',
        category: '神兽',
    },
    {
        name: '陆吾',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/luwu.png'),
        effect: '所有生灵不能速攻',
        attack: '2',
        health: '14',
        quality: '凡',
        category: '妖仙',
    },
    {
        name: '太白金星',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/taibaijinxing.png'),
        effect: '反弹',
        attack: '2',
        health: '9',
        quality: '天',
        category: '天仙',
    },
    {
        name: '七仙女',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/qixiannv.png'),
        effect: '己方主角受到的非攻击伤害-3',
        attack: '3',
        health: '12',
        quality: '地',
        category: '天仙',
    },
    {
        name: '红衣仙女',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/hongyixiannv.png'),
        effect: '1：使一个木系或火系的生灵不能使用主动技能，再封印本生灵',
        attack: '3',
        health: '12',
        quality: '地',
        category: '天仙',
    },
    {
        name: '转世灵童',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/zhuanshilingtong.png'),
        effect: '任意一方打出费用小于或等于4的生灵牌时：其进场能力无效',
        attack: '2',
        health: '11',
        quality: '天',
        category: '佛门',
    },
    {
        name: '长臂罗汉',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/changbiluohan.png'),
        effect: '1延迟：牺牲，将敌方场上一个装备放入己方手牌',
        attack: '3',
        health: '11',
        quality: '天',
        category: '佛门',
    },
    {
        name: '护教伽蓝',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/hujiaoqielan.png'),
        effect: '己方主角和生灵受到的非攻击伤害-1',
        attack: '2',
        health: '15',
        quality: '地',
        category: '佛门',
    },
    {
        name: '宁采臣',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/ningcaicheng.png'),
        effect: '场上每有一个衍生生灵，本生灵的攻击+1',
        attack: '2',
        health: '13',
        quality: '地',
        category: '异人',
    },
    {
        name: '金甲卫士',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/jinjiaweishi.png'),
        effect: '任意装备离场时：本生灵攻击对峙生灵及其相邻生灵',
        attack: '3',
        health: '12',
        quality: '地',
        category: '天将',
    },
    {
        name: '蟠桃仙女',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/pantaoxiannv.png'),
        effect: '0：使一个其他神官或天仙类生灵生命+1，攻击+1，直到回合结束',
        attack: '3',
        health: '10',
        quality: '天',
        category: '天仙',
    },
    {
        name: '接引童子',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/jieyingtongzi.png'),
        effect: '己方其他佛门类生灵进场时：使其攻击+1；己方佛门类生灵离场时：本生灵的生命+2',
        attack: '2',
        health: '11',
        quality: '地',
        category: '佛门',
    },
    {
        name: '善财童子',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/shancaitongzi.png'),
        effect: '0：本生灵支付3点生命，向己方牌库洗入一张【因缘·善】',
        attack: '2',
        health: '16',
        quality: '地',
        category: '佛门',
    },
    {
        name: '金龙吟',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/shancaitongzi.png'),
        effect: '使一个生灵的生命+5，若其生命依然小于等于对峙生灵，则本卡回手',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '龙象般若',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/longxiangbanruo.png'),
        effect: '消灭攻击大于对峙生灵的的所有生灵，每个被消灭的生灵都会使其操纵者抽一张牌。',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '不动明王咒',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/budongmingwangzhou.png'),
        effect: '消灭所有沉睡生灵',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '倒虹吸',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/daohongxi.png'),
        effect: '将场上一个装备放入己方手牌',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '霹雳三打',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/pilisanda.png'),
        effect: '使一个生灵及其相邻生灵的生命-x，x为所选生灵的费用',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '梦蝶',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/mengdie.png'),
        effect: '使一个生灵沉睡，直到敌方回合结束，再抽一张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '追梦',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/zhuimeng.png'),
        effect: '场上每有一个沉睡生灵，就抽一张牌',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '往生咒',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/wangshengzhou.png'),
        effect: '消灭连锁区的生灵牌和装备牌（己方场上佛门类生灵数量>=3才可使用）',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '多心经',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/duoxinjing.png'),
        effect: '场上每有一个具有主动技能的己方生灵，就抽一张牌（最多三张）',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '经纶三转',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/jinglunsanzhuan.png'),
        effect: '所有地方生灵的生命-3x，x为各自费用与攻击的差值',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '画地为牢',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/huadiweilao.png'),
        effect: '使一个生灵的攻击变为0，直到地方回合结束，再抽一张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '苦海无边',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/kuhaiwubian.png'),
        effect: '己方场上每有一个费用大于或等于6的生灵，就随机消灭一个地方生灵',
        attack: '',
        health: '',
        quality: '地',
        category: '法术',
    },
    {
        name: '万众一心',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/wanzhongyixin.png'),
        effect: '所有攻击小于或等于3的己方生灵的攻击变为4，直到回合结束',
        attack: '',
        health: '',
        quality: '凡',
        category: '法术',
    },
    {
        name: '逆风刀',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/nifengdao.png'),
        effect: '地方打出稀有卡时触发：消灭该稀有卡',
        attack: '',
        health: '',
        quality: '凡',
        category: '触发法术',
    },
    {
        name: '呼朋引伴',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/hupengyinban.png'),
        effect: '将牌库一张随机异人类生灵加入手牌；若己方手牌有灵玉，则弃一张，且效果改为两张',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '披沙炼金',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/pishalianjin.png'),
        effect: '将任意废牌堆中的一张装备牌放入己方手牌，获得一张灵玉',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '金蝉脱壳',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/jinchantuoqiao.png'),
        effect: '复制一个己方生灵到己方手牌，再将其变化为逍遥笛仙',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '壮烈成仁',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/zhuangliechengren.png'),
        effect: '消灭一个己方英魂类生灵：消灭连锁区所有地方法术',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '铸剑为犁',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/zhujianweili.png'),
        effect: '二选一：使一个生灵的攻击变为1；或消灭一个装备',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '魂颠梦倒',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/hundianmengdao.png'),
        effect: '使一个生灵装备一个刀盾，再使其对峙生灵获得沉睡。直到地方回合结束',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '七宝玲珑塔',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/qibaolinglongta.png'),
        effect: '己方回合开始时：若上一回合中己方主角受到的伤害大于7，则抽两张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '主角装备',
    },
    {
        name: '震天弓',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/zhentiangong.png'),
        effect: '3：消灭一个装备',
        attack: '',
        health: '',
        quality: '地',
        category: '主角装备',
    },
    {
        name: '乾坤圈',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/qiankunquan.png'),
        effect: '己方回合开始时：己方所有攻击最低的生灵的攻击+1',
        attack: '',
        health: '',
        quality: '凡',
        category: '主角装备',
    },
    {
        name: '祖传宝剑',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/zuchuanbaojian.png'),
        effect: '所装备生灵获得：攻击+2且死亡时：操纵者获得一张【祖传宝剑】',
        attack: '',
        health: '',
        quality: '地',
        category: '生灵装备',
    },
    {
        name: '香火台',
        attr: 1,
        cost: 2,
        imgUrl: require('../assets/cardImg/xianghuotai.png'),
        effect: '3：祈求1张天仙、天将或神官（己方场上天仙、天将或神官类生灵数量>=3时才能使用）',
        attack: '',
        health: '',
        quality: '地',
        category: '主角装备',
    },
    {
        name: '鹿力大仙',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/lulidaxian.png'),
        effect: '其他生灵进场时：本生灵的攻击+1，生命-1',
        attack: '1',
        health: '13',
        quality: '地',
        category: '妖怪',
    },
    {
        name: '百花羞',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/baihuaxiu.png'),
        effect: '使一个火系或水系生灵的攻击+2，直到回合结束',
        attack: '2',
        health: '12',
        quality: '凡',
        category: '异人',
    },
    {
        name: '小青',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/xiaoqin.png'),
        effect: '进场时：己方修为+1；离场时：地方修为+1',
        attack: '2',
        health: '9',
        quality: '天',
        category: '妖仙',
    },
    {
        name: '百眼魔君',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/baiyanmojun.png'),
        effect: '2：攻击+3，直到回合结束（可连续使用）',
        attack: '3',
        health: '12',
        quality: '天',
        category: '妖怪',
    },
    {
        name: '比丘美后',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/biqiumeihou.png'),
        effect: '攻击3次；不能被己方卡牌或技能选为目标',
        attack: '1',
        health: '11',
        quality: '凡',
        category: '妖怪',
    },
    {
        name: '玉面狐狸精',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/yumianhulijing.png'),
        effect: '穿透；基础攻击等于己方生灵数量',
        attack: '？',
        health: '6',
        quality: '天',
        category: '妖仙',
    },
    {
        name: '婴宁',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/yinning.png'),
        effect: '穿透；基础攻击等于己方生灵数量',
        attack: '？',
        health: '6',
        quality: '天',
        category: '妖仙',
    },
    {
        name: '猴元帅',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/houyuanshuai.png'),
        effect: '',
        attack: '3',
        health: '13',
        quality: '凡',
        category: '妖怪',
    },
    {
        name: '红鳞巨蟒',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/honglingjumang.png'),
        effect: '攻击+x，x为己方当前法力',
        attack: '3',
        health: '8',
        quality: '凡',
        category: '神兽',
    },
    {
        name: '伶俐虫',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/linglichong.png'),
        effect: '进场时：若地方生灵数量大于己方，则己方主角生命+4',
        attack: '3',
        health: '11',
        quality: '地',
        category: '妖怪',
    },
    {
        name: '雷击木',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/leijimu.png'),
        effect: '1：牺牲，在原位置衍生惊雷神将',
        attack: '3',
        health: '12',
        quality: '地',
        category: '妖怪',
    },
    {
        name: '虞姬',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/yuji.png'),
        effect: '单回合内，任意一方最多只能抽两张牌',
        attack: '3',
        health: '12',
        quality: '天',
        category: '异人',
    },
    {
        name: '百足虫',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/baizuchong.png'),
        effect: '地方回合开始时：己方法力+1',
        attack: '3',
        health: '10',
        quality: '地',
        category: '妖怪',
    },
    {
        name: '仙猿',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/xianyuan.png'),
        effect: '己方生灵不能被地方生灵选为目标',
        attack: '3',
        health: '12',
        quality: '地',
        category: '神兽',
    },
    {
        name: '伴忠猎犬',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/banzhongliequan.png'),
        effect: '己方回合开始时：若没有费用>=3的相邻生灵，则本生灵沉睡，直到回合结束',
        attack: '4',
        health: '13',
        quality: '凡',
        category: '神兽',
    },
    {
        name: '祝英台',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/zhuyingtai.png'),
        effect: '穿透；己方场上有梁山伯时，攻击+1',
        attack: '2',
        health: '13',
        quality: '地',
        category: '异人',
    },
    {
        name: '幻彩娥',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/huancaie.png'),
        effect: '进场时：本生灵生命-4；地方打出法术牌后：攻击+1，生命+2',
        attack: '2',
        health: '15',
        quality: '天',
        category: '妖仙',
    },
    {
        name: '巨蜂',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/jufeng.png'),
        effect: '进场时：封印一个生灵，直到地方回合结束；借法：改为永久封印',
        attack: '3',
        health: '7',
        quality: '地',
        category: '神兽',
    },
    {
        name: '花木兰',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/huamulan.png'),
        effect: '地方打出以场上生灵牌为目标的法术牌时：将其目标改为本生灵',
        attack: '3',
        health: '11',
        quality: '地',
        category: '英魂',
    },
    {
        name: '狐女娇娜',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/hunvjiaona.png'),
        effect: '',
        attack: '3',
        health: '13',
        quality: '凡',
        category: '妖怪',
    },
    {
        name: '瓶中狐',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/pingzhonghu.png'),
        effect: '0：将一张手牌洗入牌库，获得一张伏击',
        attack: '2',
        health: '13',
        quality: '地',
        category: '妖怪',
    },
    {
        name: '花姑子',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/huaguzi.png'),
        effect: '进场时：向己方牌库洗入x张【因缘·仁】，x为己方场上的生灵数量（最多三张）',
        attack: '3',
        health: '11',
        quality: '地',
        category: '妖仙',
    },
    {
        name: '疯魔三笑',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/fengmosanxiao.png'),
        effect: '使一个生灵的攻击+6，直到回合结束',
        attack: '',
        health: '',
        quality: '凡',
        category: '法术',
    },
    {
        name: '妙手回春',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/miaoshouhuichun.png'),
        effect: '使一个生灵的生命+6，再抽一张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '红袖添香',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/hongxiutianxiang.png'),
        effect: '己方场上每比地方少一个生灵，就抽一张牌（最多三张）',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '花开并蒂',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/huakaibingdi.png'),
        effect: '再连锁区的生灵将进入的空位对面，衍生相同生灵',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '魅惑',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/meihuo.png'),
        effect: '抽一张牌；若连锁区的上一张牌是有进场能力的生灵牌，使其进场能力无效',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '协力',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/xieli.png'),
        effect: '使一个生灵及其相邻生灵的攻击+2，直到回合结束',
        attack: '',
        health: '',
        quality: '凡',
        category: '法术',
    },
    {
        name: '禁魔之光',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/jinmozhiguang.png'),
        effect: '地方生灵进场时触发：封印该生灵，己方抽一张牌（不影响进场能力）',
        attack: '',
        health: '',
        quality: '天',
        category: '触发法术',
    },
    {
        name: '齐心',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/qixin.png'),
        effect: '使一个生灵及其相同名的生灵攻击+3，直到回合结束',
        attack: '',
        health: '',
        quality: '凡',
        category: '法术',
    },
    {
        name: '三阳开泰',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/sanyangkaitai.png'),
        effect: '己方修为变为与地方相同',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '空灵刺',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/konglingci.png'),
        effect: '二选一：消灭一个装备；或封印一个生灵',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '南疆符法',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/nanjiangfufa.png'),
        effect: '所有己方生灵的生命+3，抽一张牌',
        attack: '',
        health: '',
        quality: '地',
        category: '法术',
    },
    {
        name: '野性召唤',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/yexingzhaohuan.png'),
        effect: '从己方牌库选择一张妖怪、妖仙或神兽类生灵牌放入己方手牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '蝶舞天涯',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/diewutianya.png'),
        effect: '己方生灵的生命和攻击+2并获得透骨，直到回合结束（己方场上和废牌堆有祝英台和梁山伯才能使用）',
        attack: '',
        health: '',
        quality: '凡',
        category: '法术',
    },
    {
        name: '自然秩序',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/ziranzhixu.png'),
        effect: '从敌方牌库中选择一张牌，消灭地方牌库中所有的同名卡牌',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '莲花印',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/lianhuayin.png'),
        effect: '封印一个生灵；借力：抽一张牌',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '物竞天择',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/wujingtianze.png'),
        effect: '随机使一方的修为变为与另一方相同',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '万象更新',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/wanxianggengxin.png'),
        effect: '随即将己方一张费用最低的手牌洗入牌库，再抽两张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '繁花似锦·纪',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/fanhuasijing.png'),
        effect: '复制己方场上和手牌中的所有纪念卡到己方手牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '法术',
    },
    {
        name: '宝莲灯',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/baoliandeng.png'),
        effect: '2：使一个生灵的攻击+3，直到回合结束',
        attack: '',
        health: '',
        quality: '凡',
        category: '主角装备',
    },
    {
        name: '青萍剑',
        attr: 2,
        cost: 2,
        imgUrl: require('../assets/cardImg/qingpinjian.png'),
        effect: '所装备生灵获得：攻击+2，透骨，且己方回合结束时，生命+2',
        attack: '',
        health: '',
        quality: '地',
        category: '生灵装备',
    },
    {
        name: '云霄娘娘',
        attr: 3,
        cost: 2,
        imgUrl: require('../assets/cardImg/yunxiaoniangniang.png'),
        effect: '3，延迟：抽一张牌，回手',
        attack: '1',
        health: '15',
        quality: '天',
        category: '散仙',
    },
    {
        name: '哪吒',
        attr: 3,
        cost: 2,
        imgUrl: require('../assets/cardImg/neza.png'),
        effect: '进场时：与一个己方生灵换位；？，延迟：与对峙生灵一起回手（需支付其费用）',
        attack: '3',
        health: '12',
        quality: '天',
        category: '散仙',
    },
    {
        name: '巡海夜叉',
        attr: 3,
        cost: 2,
        imgUrl: require('../assets/cardImg/xunhaiyecha.png'),
        effect: '1：为己方牌库顶的3张牌排序',
        attack: '2',
        health: '15',
        quality: '凡',
        category: '水族',
    },
    {
        name: '鲤鱼精',
        attr: 3,
        cost: 2,
        imgUrl: require('../assets/cardImg/liyujing.png'),
        effect: '地方生灵进场时：该生灵的生命-9，本生灵的生命-5',
        attack: '2',
        health: '10',
        quality: '凡',
        category: '水族',
    },
    {
        name: '洛神',
        attr: 3,
        cost: 2,
        imgUrl: require('../assets/cardImg/luoshen.png'),
        effect: '地方生灵进场时：该生灵的生命-3',
        attack: '2',
        health: '9',
        quality: '凡',
        category: '散仙',
    },
    {
        name: '修身道人',
        attr: 3,
        cost: 2,
        imgUrl: require('../assets/cardImg/xiushendaoren.png'),
        effect: '进场时：地方修为每比己方高2点，己方就装备一个风火蒲团',
        attack: '3',
        health: '10',
        quality: '天',
        category: '异人',
    },
    {
        name: '寿星',
        attr: 3,
        cost: 2,
        imgUrl: require('../assets/cardImg/shouxing.png'),
        effect: '替己方主角承受地方造成的非攻击伤害',
        attack: '1',
        health: '19',
        quality: '地',
        category: '散仙',
    },
    {
        name: '虾将',
        attr: 3,
        cost: 2,
        imgUrl: require('../assets/cardImg/xiajiang.png'),
        effect: '1：使对峙生灵与另一个地方生灵换位',
        attack: '3',
        health: '12',
        quality: '地',
        category: '水族',
    },
    {
        name: '犬目仙童',
        attr: 3,
        cost: 2,
        imgUrl: require('../assets/cardImg/quanmuxiantong.png'),
        effect: '进场时：查看己方牌库顶的牌，若是生灵牌，则将其消灭，否则放入手牌',
        attack: '3',
        health: '9',
        quality: '凡',
        category: '散仙',
    },
    {
        name: '崂山道士',
        attr: 3,
        cost: 2,
        imgUrl: require('../assets/cardImg/laoshandaoshi.png'),
        effect: '地方打出有进场能力的生灵牌时：己方法力+2',
        attack: '2',
        health: '14',
        quality: '地',
        category: '散仙',
    },
    {
        name: '孟姜女',
        attr: 3,
        cost: 2,
        imgUrl: require('../assets/cardImg/mengjiangnv.png'),
        effect: '进场时：使一个费用小于或等于3的地方生灵变为衍生状态',
        attack: '3',
        health: '11',
        quality: '地',
        category: '异人',
    },
    {
        name: '珊瑚镜',
        attr: 3,
        cost: 2,
        imgUrl: require('../assets/cardImg/shanhujing.png'),
        effect: '0：使一个生灵不能被选为目标，直到地方回合结束',
        attack: '2',
        health: '15',
        quality: '地',
        category: '水族',
    },
    {
        name: '丑道士',
        attr: 3,
        cost: 2,
        imgUrl: require('../assets/cardImg/choudaoshi.png'),
        effect: '1：从敌方废牌堆中选择1张牌洗入己方牌库',
        attack: '3',
        health: '11',
        quality: '地',
        category: '异人',
    },
    {
        name: '鬼谷子',
        attr: 3,
        cost: 2,
        imgUrl: require('../assets/cardImg/guiguzi.png'),
        effect: '0：将一张手牌洗入牌库，随机牌库中的一张牌放入手牌',
        attack: '2',
        health: '13',
        quality: '天',
        category: '异人',
    },
    {
        name: '真武龟将军',
        attr: 3,
        cost: 2,
        imgUrl: require('../assets/cardImg/zhenwuguijiangjun.png'),
        effect: '进场时：若对峙生灵的费用<=2，则使对峙生灵回手',
        attack: '3',
        health: '10',
        quality: '地',
        category: '神官',
    },
    {
        name: '碧霄娘娘',
        attr: 3,
        cost: 2,
        imgUrl: require('../assets/cardImg/bixiaoniangniang.png'),
        effect: '穿透；己方手牌数量大于或等于地方时，不能被选为目标',
        attack: '2',
        health: '12',
        quality: '凡',
        category: '散仙',
    },
    {
        name: '福星',
        attr: 3,
        cost: 2,
        imgUrl: require('../assets/cardImg/fuxing.png'),
        effect: '进场时：随机复制地方手牌中的1张非衍生法术牌到己方手牌',
        attack: '2',
        health: '8',
        quality: '地',
        category: '散仙',
    },
    {
        name: '长孙无忌',
        attr: 3,
        cost: 2,
        imgUrl: require('../assets/cardImg/zhangsunwuji.png'),
        effect: '1：弃一张灵玉：抽一张牌且本回合结束时，己方法力+2',
        attack: '3',
        health: '12',
        quality: '凡',
        category: '英魂',
    },
    {
        name: '蛰龙',
        attr: 3,
        cost: 2,
        imgUrl: require('../assets/cardImg/chilong.png'),
        effect: '进场时：借力：祈求一张法术牌',
        attack: '3',
        health: '10',
        quality: '天',
        category: '水族',
    },
    {
        name: '魁星',
        attr: 3,
        cost: 2,
        imgUrl: require('../assets/cardImg/kuixing.png'),
        effect: '回合结束时：若己方有多余法力，就向牌库中洗入一张【因缘·智】',
        attack: '2',
        health: '15',
        quality: '地',
        category: '神官',
    },
]

export { CardList }