/** 
 * @name 卡牌名称
 * @attr 卡牌的五行属性
 * @cost 使用卡牌所需费用
 * @imgUrl  卡牌插画
 * @effect 卡牌效果
 * @attack 攻击力
 * @health 生命值
 * @quality 卡牌的品质
 * @category 卡牌类别
*/
const CardList = [
    {
        name: '织女',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/zhinv.png'),
        effect: '1：使一个生灵攻击力-3，直到敌方回合结束',
        attack: '1',
        health: '9',
        quality: '凡',
        category: '天仙',
    },
    {
        name: '纠察灵官',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/jiuchalingguan.png'),
        effect: '敌方生灵的攻击力减一',
        attack: '0',
        health: '9',
        quality: '地',
        category: '天将',
    },
    {
        name: '玉兔',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/yutu.png'),
        effect: '免疫攻击伤害',
        attack: '2',
        health: '7',
        quality: '天',
        category: '妖仙',
    },
    {
        name: '棍僧',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/gunseng.png'),
        effect: '群攻对峙生灵及其相邻生灵',
        attack: '2',
        health: '9',
        quality: '凡',
        category: '佛门',
    },
    {
        name: '峨眉女尼',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/emeinvni.png'),
        effect: '免疫非攻击伤害',
        attack: '3',
        health: '7',
        quality: '凡',
        category: '佛门',
    },
    {
        name: '悬壶医女',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/xuanhuyinv.png'),
        effect: '进场时：使一个生灵的生命加三',
        attack: '3',
        health: '7',
        quality: '凡',
        category: '异人',
    },
    {
        name: '天庭甲士',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/tiantingjiashi.png'),
        effect: '进场时：使一个己方生灵的攻击加一',
        attack: '2',
        health: '7',
        quality: '地',
        category: '天将',
    },
    {
        name: '蔡文姬',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/caiwenji.png'),
        effect: '己方主角的生命<=17时，己方生灵受到的伤害-1',
        attack: '3',
        health: '7',
        quality: '凡',
        category: '异人',
    },
    {
        name: '吐宝鼠',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/tubaoshu.png'),
        effect: '死亡时：己方主角生命+2，并获得一张灵玉',
        attack: '2',
        health: '8',
        quality: '天',
        category: '神兽',
    },
    {
        name: '气疗术',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/qiliaoshu.png'),
        effect: '己方主角生命+2，抽一张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '法术',
    },
    {
        name: '五气朝元',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/wuqichaoyuan.png'),
        effect: '耗尽法力：己方主角的生命值+2x，x为消耗的法力值，然后法力值+1',
        attack: '',
        health: '',
        quality: '凡',
        category: '法术',
    },
    {
        name: '反噬',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/fanshi.png'),
        effect: '使一个生灵获得反弹直到敌方回合结束，再抽一张牌。',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '碎羽祭',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/suiyuji.png'),
        effect: '消灭己方的一个装备，来消灭连锁区的生灵和装备卡',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '圣兽守护',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/shengshoushouhu.png'),
        effect: '使一个生灵免疫非攻击伤害直到敌方回合结束，再抽一张牌',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '破玉爪',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/poyuzhua.png'),
        effect: '消灭一个己方装备，再抽两张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '禅海截心',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/chanhaijiexin.png'),
        effect: '己方主角生命+6，敌方修为比己方>=2时，获得一张截心咒',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '妙法莲华',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/miaofalianhua.png'),
        effect: '将本回合内己方进入废牌堆的生灵放入己方手牌',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '六字大明咒',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/liuzidamingzhou.png'),
        effect: '敌方打出装备牌时触发：将该装备放入己方手牌，再抽一张牌',
        attack: '',
        health: '',
        quality: '地',
        category: '触发法术',
    },
    {
        name: '燕双飞',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/yanshuangfei.png'),
        effect: '依次选择两个生灵：第一个生命+4，第二个+8',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '禅定',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/chanding.png'),
        effect: '使一个生灵沉睡。或者使一个生灵的相邻生灵沉睡，直到敌方回合结束',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '食梦',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/shimeng.png'),
        effect: '抽一张卡，己方主角生命值增加场上沉睡生灵数x2',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '浩然正气',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/haoranzhengqi.png'),
        effect: '己方所有生灵获得反弹，直到敌方回合结束',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '闭口禅',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/bikouchan.png'),
        effect: '选择一个己方生灵，并抽一张牌。若所选生灵生命值等于1，则所有己方生灵生命回满',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '拈花指',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/nianhuazhi.png'),
        effect: '从敌方牌库中选择一张装备卡放入己方手牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '法术',
    },
    {
        name: '落日神箭',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/luorishenjian.png'),
        effect: '消灭一个带有装备的生灵',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '再造',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/zaizao.png'),
        effect: '复制一个场上的非金系的装备放入己方手牌',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '坐禅',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/zuochan.png'),
        effect: '获得1+x张风火蒲团，敌方修为每比己方高2，x+1',
        attack: '',
        health: '',
        quality: '天',
        category: '法术',
    },
    {
        name: '祛邪佛光',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/quxiefoguang.png'),
        effect: '抽一张牌，借力：消灭所有费用<=2的衍生生灵',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '上上签',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/shangshangqian.png'),
        effect: '将己方手牌和牌库的同名卡放入废牌堆，再抽一张卡，若当前为偶数回合，则己方法力+2',
        attack: '',
        health: '',
        quality: '凡',
        category: '法术',
    },
    {
        name: '天庭禁令',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/tiantingjinling.png'),
        effect: '本回合内，敌方最多只能抽一张卡。（连锁区有牌时才能使用）',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '宝玉招财',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/baoyuzhaocai.png'),
        effect: '己方生命+3，获得一张灵玉',
        attack: '',
        health: '',
        quality: '地',
        category: '法术',
    },
    {
        name: '千里婵娟-纪',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/qianlichanjuan.png'),
        effect: '本回合内己方主角恢复生命时：再恢复一次相同数量的生命',
        attack: '',
        health: '',
        quality: '天',
        category: '法术',
    },
    {
        name: '九环锡杖',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/jiuhuanxizhang.png'),
        effect: '己方回合开始时：若己方主角的生命<9，则生命+9',
        attack: '',
        health: '',
        quality: '天',
        category: '主角装备',
    },
    {
        name: '锦襕袈裟',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/jinglanjiasha.png'),
        effect: '操控者，所装备生灵及其相邻生灵所受到的非攻击伤害-4',
        attack: '',
        health: '',
        quality: '天',
        category: '生灵装备',
    },
    {
        name: '仙豆',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/xiandou.png'),
        effect: '己方主角受到攻击伤害后：生命+1',
        attack: '',
        health: '',
        quality: '地',
        category: '主角装备',
    },
    {
        name: '岐牛神鼓',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/qiniushengu.png'),
        effect: '锁装备生灵及其相邻生灵获得反弹',
        attack: '',
        health: '',
        quality: '凡',
        category: '生灵装备',
    },
    {
        name: '刀盾',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/daodun.png'),
        effect: '所装备生灵获得反弹，且免疫敌方造成的非攻击伤害',
        attack: '',
        health: '',
        quality: '凡',
        category: '生灵装备',
    },
    {
        name: '五行月饼-纪',
        attr: 1,
        cost: 1,
        imgUrl: require('../assets/cardImg/wuxingyuebing.png'),
        effect: '己方回合开始时：己方主角和生灵生命+1，从场上进入废牌堆时，改为放入敌方手牌',
        attack: '',
        health: '',
        quality: '天',
        category: '主角装备',
    },
    {
        name: '羊力大仙',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/yanglidaxian.png'),
        effect: '击伤对手后：攻击+1',
        attack: '2',
        health: '10',
        quality: '凡',
        category: '妖怪',
    },
    {
        name: '小猴精',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/xiaohoujing.png'),
        effect: '己方生灵数量>=3时，攻击+2',
        attack: '1',
        health: '10',
        quality: '凡',
        category: '妖怪',
    },
    {
        name: '青牛精',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/qinniujing.png'),
        effect: '对峙生灵费用>=4时，本生灵不能攻击',
        attack: '4',
        health: '7',
        quality: '地',
        category: '妖仙',
    },
    {
        name: '月宫小强',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/yuegongxiaoqiang.png'),
        effect: '1：牺牲：在相邻空位衍生同名生灵',
        attack: '3',
        health: '3',
        quality: '天',
        category: '异灵',
    },
    {
        name: '铁背苍狼精',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/tiebeicanglangjing.png'),
        effect: '衍生生灵进场时：本生灵攻击+1，生命-1',
        attack: '2',
        health: '11',
        quality: '凡',
        category: '妖怪',
    },
    {
        name: '杏仙',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/xingxian.png'),
        effect: '',
        attack: '3',
        health: '7',
        quality: '凡',
        category: '妖仙',
    },
    {
        name: '蜘蛛精',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/zhizhujing.png'),
        effect: '死亡时：在原位置衍生一个随机的一废生灵',
        attack: '2',
        health: '6',
        quality: '地',
        category: '妖怪',
    },
    {
        name: '凤翼天翔',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/fengyitianxiang.png'),
        effect: '使一个生灵获得穿透，直到回合结束',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '天山折梅',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/tianshanzhemei.png'),
        effect: '复制一个敌方生灵或者一个己方木系生灵到己方手牌',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '枯木生花',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/kumushenghua.png'),
        effect: '使一个生灵的攻击+2，并将敌方废牌堆所有卡牌移除游戏',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '落花流水',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/luohualiushui.png'),
        effect: '敌方回合内，己方弃牌时触发：己方抽三张牌',
        attack: '',
        health: '',
        quality: '地',
        category: '触发法术',
    },
    {
        name: '倒卷帘',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/daojuanlian.png'),
        effect: '敌方打出费用>=5的法术牌时触发：消灭该法术',
        attack: '',
        health: '',
        quality: '天',
        category: '触发法术',
    },
    {
        name: '祝由秘技',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/zhuyoumiji.png'),
        effect: '己方主角生命+x，x为己方修为',
        attack: '',
        health: '',
        quality: '地',
        category: '法术',
    },
    {
        name: '同气连枝',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/tongqilianzhi.png'),
        effect: '选择一个生灵，使所有生灵的类别变为与其相同，再抽一张牌',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '叠翠',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/diecui.png'),
        effect: '使一个生灵攻击次数+1，直到回合结束',
        attack: '',
        health: '',
        quality: '天',
        category: '法术',
    },
    {
        name: '碾压',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/nianya.png'),
        effect: '使所有己方生灵攻击+1，并获得透骨，直到回合结束',
        attack: '',
        health: '',
        quality: '地',
        category: '法术',
    },
    {
        name: '野狐禅',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/yehuchan.png'),
        effect: '敌方打出的法术与己方场上某生灵费用相同时触发：消灭该法术，己方修为+1',
        attack: '',
        health: '',
        quality: '地',
        category: '触发法术',
    },
    {
        name: '枯荣决',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/kurongjue.png'),
        effect: '若敌方修为比己方修为多2点及以上，则己方修为+2',
        attack: '',
        health: '',
        quality: '天',
        category: '法术',
    },
    {
        name: '西天取经',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/xitianqujing.png'),
        effect: '若己方场上同时存在唐三藏，沙和尚，孙悟空，猪八戒。则己方获得胜利',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '昙花一现',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/tanhuayixian.png'),
        effect: '敌方打出3费卡牌时，若己方生灵数>=敌方时触发：消灭该卡牌',
        attack: '',
        health: '',
        quality: '天',
        category: '触发法术',
    },
    {
        name: '子夜留香',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/ziyeliuxiang.png'),
        effect: '若敌方修为>=己方，则己方修为+1，否则双方修为+1',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '封禅',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/fengshan.png'),
        effect: '封印一个己方生灵再抽一张卡。或封印己方所有生灵再抽一张卡',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '绝处逢生',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/juechufengsheng.png'),
        effect: '己方主角生命+5，若没有手牌，则抽一张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '触景生情',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/chujingshengqing.png'),
        effect: '从己方牌库中选择一张触发法术放入己方手牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '法术',
    },
    {
        name: '书山有路',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/shushanyoulu.png'),
        effect: '抽一张牌，直到回合结束，己方生灵每使用一次主动技能攻击永久+1',
        attack: '',
        health: '',
        quality: '凡',
        category: '法术',
    },
    {
        name: '恶作剧',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/ezuoju.png'),
        effect: '敌方打出装备牌时触发：消灭该装备，并将牌库中一张随机妖仙生灵加入手牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '触发法术',
    },
    {
        name: '山中无老虎',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/shanzhongwulaohu.png'),
        effect: '本卡被弃掉时触发：在己方随机空位衍生小猴精，再抽一张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '触发法术',
    },
    {
        name: '借力打力',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/jielidali.png'),
        effect: '使一个生灵攻击+1，下一个己方回合开始时：获得一张同名衍生卡',
        attack: '',
        health: '',
        quality: '地',
        category: '法术',
    },
    {
        name: '撞心杵',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/zhuangxinchu.png'),
        effect: '所装备生灵获得：攻击力+1，若被阻挡则改为+4',
        attack: '',
        health: '',
        quality: '凡',
        category: '生灵装备',
    },
    {
        name: '瑶光核桃',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/yaoguanghetao.png'),
        effect: '所装备生灵的攻击+2，其他己方生灵的攻击+1',
        attack: '',
        health: '',
        quality: '地',
        category: '生灵装备',
    },
    {
        name: '攒心钉',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/zanxinding.png'),
        effect: '所装备生灵获得透骨',
        attack: '',
        health: '',
        quality: '地',
        category: '生灵装备',
    },
    {
        name: '清肠稻',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/qingchangdao.png'),
        effect: '所装备生灵每回合可多使用一次生灵技能',
        attack: '',
        health: '',
        quality: '地',
        category: '生灵装备',
    },
    {
        name: '盘龙拐',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/panlongguai.png'),
        effect: '非衍生的己方生灵进场时，所装备生灵攻击+1',
        attack: '',
        health: '',
        quality: '凡',
        category: '生灵装备',
    },
    {
        name: '人参果',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/renshengguo.png'),
        effect: '所装备生灵获得：操控者回合结束时：生命+4',
        attack: '',
        health: '',
        quality: '地',
        category: '生灵装备',
    },
    {
        name: '紫金铃',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/zijinling.png'),
        effect: '0：选择两个生灵，使第一个生灵的类别变为与第二个生灵一致',
        attack: '',
        health: '',
        quality: '凡',
        category: '生灵装备',
    },
    {
        name: '斩妖剑',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/zhanyaojian.png'),
        effect: '与所装备生灵相同类别的所有己方生灵的攻击+2',
        attack: '',
        health: '',
        quality: '凡',
        category: '生灵装备',
    },
    {
        name: '如意钩',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/ruyigou.png'),
        effect: '所装备生灵获得：对其他生灵造成的伤害+2',
        attack: '',
        health: '',
        quality: '凡',
        category: '生灵装备',
    },
    {
        name: '五行粽子-纪',
        attr: 2,
        cost: 1,
        imgUrl: require('../assets/cardImg/ruyigou.png'),
        effect: '己方回合开始时：使一个生灵攻击+2，直到回合结束，从场上进入废牌堆是：改为放入敌方手牌',
        attack: '',
        health: '',
        quality: '天',
        category: '主角装备',
    },
    {
        name: '龟丞相：天明',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/guichengxiang.png'),
        effect: '进场时：抽一张牌',
        attack: '0',
        health: '8',
        quality: '凡',
        category: '水族',
    },
    {
        name: '逍遥笛仙',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/xiaoyaodixian.png'),
        effect: '受到攻击伤害且未死亡时：回手。1：进入己方其他空位',
        attack: '2',
        health: '6',
        quality: '凡',
        category: '散仙',
    },
    {
        name: '量人蛇',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/liangrenshe.png'),
        effect: '1：使一个生命小于等于本生灵的敌方生灵回手',
        attack: '1',
        health: '10',
        quality: '天',
        category: '神兽',
    },
    {
        name: '美人鱼',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/meirenyu.png'),
        effect: '进场时：与一个己方生灵换位',
        attack: '2',
        health: '9',
        quality: '凡',
        category: '水族',
    },
    {
        name: '龙宫密探',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/longgongmitan.png'),
        effect: '进场时：查看敌方牌库顶的三张牌',
        attack: '2',
        health: '9',
        quality: '凡',
        category: '水族',
    },
    {
        name: '龙鲤',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/longli.png'),
        effect: '6，延迟：牺牲，在原位置衍生天池幻龙',
        attack: '2',
        health: '9',
        quality: '地',
        category: '水族',
    },
    {
        name: '玉扇仙女',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/yushanxiannv.png'),
        effect: '进场时：若己方门派为天宫，则从己方牌库中复制5张卡牌洗入牌库',
        attack: '3',
        health: '7',
        quality: '天',
        category: '天仙',
    },
    {
        name: '猪婆龙',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/zhupolong.png'),
        effect: '穿透',
        attack: '2',
        health: '8',
        quality: '凡',
        category: '神兽',
    },
    {
        name: '螺旋劲',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/luoxuanjing.png'),
        effect: '使一个生灵与其装备一起回手',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '暗潮',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/anchao.png'),
        effect: '单回合内敌方第二次打出法术牌时触发：将该法术放入己方手牌',
        attack: '',
        health: '',
        quality: '天',
        category: '触发法术',
    },
    {
        name: '心血来潮',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/xinxuelaichao.png'),
        effect: '任意一方打出法术牌后，若联锁区卡牌数量>=3，触发：消灭连锁区的所有敌方法术牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '触发法术',
    },
    {
        name: '对对符',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/duiduifu.png'),
        effect: '抽一张牌；若己方6个生灵的费用都与其对峙生灵相同，则己方获得胜利',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '灵气旋涡',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/lingqixuanwo.png'),
        effect: '抽一张牌；消灭连锁区中以费用大于或等于5的场上生灵为目标的法术牌',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '神龙摆尾',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/shenlongbaiwei.png'),
        effect: '使一个生灵右侧的所有己方生灵回手',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '牵引术',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/qianyinshu.png'),
        effect: '连锁区中以场上生灵为目标的法术，全部重新随机指定其目标',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '乱环诀',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/luanhuanjue.png'),
        effect: '为敌方牌库顶的4张牌排序，再消灭第一张',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '小旋风',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/xiaoxuanfeng.png'),
        effect: '使任意一方所有生灵同时向右移动一格，（最右侧的生灵移动到最左侧），双方再各抽一张牌',
        attack: '',
        health: '',
        quality: '地',
        category: '法术',
    },
    {
        name: '摩云袖-纪',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/moyunxiu.png'),
        effect: '从敌方废牌堆中选择两张牌置于敌方牌库顶，己方再抽一张牌',
        attack: '',
        health: '',
        quality: '天',
        category: '法术',
    },
    {
        name: '替死符',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/tisifu.png'),
        effect: '选择一个生灵，使其获得：替施法者承受非攻击伤害，直到回合结束。再抽一张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '浪淘沙',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/langtaosha.png'),
        effect: '消灭己方牌库顶三张牌中的生灵牌，再抽一张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '炼精化气',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/lianjinghuaqi.png'),
        effect: '抽一张牌，双方法力+1',
        attack: '',
        health: '',
        quality: '地',
        category: '法术',
    },
    {
        name: '问道',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/wendao.png'),
        effect: '使一个没有主动技能的生灵复制一个生灵的主动技能，双方各抽一张牌',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '止水',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/zhishui.png'),
        effect: '消灭连锁区的上一张费用<=2的法术牌',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '惊鸿一瞥',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/jinghongyipie.png'),
        effect: '查看己方牌库顶的两张牌，选择其中一张放入手牌，另外一张置于牌库底',
        attack: '',
        health: '',
        quality: '天',
        category: '法术',
    },
    {
        name: '梦幻泡影',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/menghuanpaoying.png'),
        effect: '从敌方手牌中选择一张牌洗入敌方牌库并洗牌，然后敌方抽一张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '遮天',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/zhetian.png'),
        effect: '己方生灵不再能被选为目标，直到敌方回合结束，再抽一张牌',
        attack: '',
        health: '',
        quality: '地',
        category: '连锁法术',
    },
    {
        name: '红杏出墙',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/hongxingchuqiang.png'),
        effect: '抽一张牌，将一张杏仙放入敌方牌库并洗牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '炼神还虚',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/lianshenhuanxu.png'),
        effect: '抽一张牌，然后弃掉手牌中所有灵玉并抽等量的牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '法术',
    },
    {
        name: '炼气化神',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/lianqihuashen.png'),
        effect: '抽一张牌，耗尽法力，每消耗两点就获得一张灵玉',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '定海神珠',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/dinghaishenzhu.png'),
        effect: '1：手牌小于等于6的玩家抽一张牌',
        attack: '',
        health: '',
        quality: '凡',
        category: '主角装备',
    },
    {
        name: '五仙汤',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/wuxiantang.png'),
        effect: '己方打出3费法术牌后，若己方当前法力小于等于己方修为，则己方法力+1（一回合十次）',
        attack: '',
        health: '',
        quality: '地',
        category: '主角装备',
    },
    {
        name: '扫霞衣',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/saoxiayi.png'),
        effect: '所装备生灵获得：受到攻击伤害且为死亡时：本生灵回手，再将对峙生灵放回其操控者的牌库顶',
        attack: '',
        health: '',
        quality: '地',
        category: '生灵装备',
    },
    {
        name: '金丹砂',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/jindansha.png'),
        effect: '敌方生灵无法速攻，穿透，吸血',
        attack: '',
        health: '',
        quality: '地',
        category: '主角装备',
    },
    {
        name: '遁龙桩',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/dunlongzhuang.png'),
        effect: '所装备生灵获得：操控者回合开始时：与一个己方生灵换位',
        attack: '',
        health: '',
        quality: '地',
        category: '生灵装备',
    },
    {
        name: '玲珑内丹',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/linglongneidan.png'),
        effect: '己方回合开始时：若己方没有手牌，则额外抽一张牌',
        attack: '',
        health: '',
        quality: '地',
        category: '生灵装备',
    },
    {
        name: '观星仪',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/guanxingyi.png'),
        effect: '进场时：借力：抽一张牌；1为己方牌库顶的三张牌排序',
        attack: '',
        health: '',
        quality: '天',
        category: '主角装备',
    },
    {
        name: '精囊妙计',
        attr: 3,
        cost: 1,
        imgUrl: require('../assets/cardImg/jingnangmiaoji.png'),
        effect: '己方回合开始时，若场上有费用>=6的生灵，则消灭本装备并选择牌库中一张法术牌加入手牌',
        attack: '',
        health: '',
        quality: '天',
        category: '主角装备',
    },
    {
        name: '天煞星',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/tianshaxing.png'),
        effect: '进场时：若己方修为<=1，则己方主角的生命-3',
        attack: '3',
        health: '9',
        quality: '凡',
        category: '神官',
    },
    {
        name: '精卫鸟',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/jingweiniao.png'),
        effect: '还击',
        attack: '2',
        health: '9',
        quality: '凡',
        category: '神兽',
    },
    {
        name: '牛虱',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/niushi.png'),
        effect: '速攻；击伤对手后：本生灵生命-3',
        attack: '3',
        health: '6',
        quality: '凡',
        category: '妖怪',
    },
    {
        name: '武吉',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/wuji.png'),
        effect: '本生灵给对手造成的攻击伤害加倍',
        attack: '2',
        health: '10',
        quality: '天',
        category: '异人',
    },
    {
        name: '闪电貂',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/shandiandiao.png'),
        effect: '进场时：本生灵的生命-2',
        attack: '3',
        health: '9',
        quality: '凡',
        category: '雷神',
    },
    {
        name: '单雄信',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/shanxiongxin.png'),
        effect: '速攻；己方回合开始时，若己方场上有攻击>=5的生灵，攻击+1，直到回合结束',
        attack: '2',
        health: '9',
        quality: '凡',
        category: '英魂',
    },
    {
        name: '雷霆一击',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/leitingyiji.png'),
        effect: '若敌方修为大于己方，则敌方修为-1，否则双方修为-1',
        attack: '',
        health: '',
        quality: '天',
        category: '连锁法术',
    },
    {
        name: '逆修斩',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/nixiuzhan.png'),
        effect: '敌方使用法术抽牌时触发：敌方修为-1，己方抽一张牌',
        attack: '',
        health: '',
        quality: '地',
        category: '触发法术',
    },
    {
        name: '飞剑',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/feijian.png'),
        effect: '使一个生灵的生命-8',
        attack: '',
        health: '',
        quality: '凡',
        category: '连锁法术',
    },
    {
        name: '霹雳火',
        attr: 4,
        cost: 1,
        imgUrl: require('../assets/cardImg/pilihuo.png'),
        effect: '对手生命-5',
        attack: '',
        health: '',
        quality: '凡',
        category: '法术',
    },
]

export { CardList }